---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneymaker-app
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
      - name: loan
        image: docker.io/kostiscodefresh/loan:{{CF_SHORT_REVISION}} 
        ports:
        - containerPort: 8080
        livenessProbe:
          timeoutSeconds: 8
          periodSeconds: 30
          httpGet:
            path: /health/live
            port: 8080
        readinessProbe:
          timeoutSeconds: 8
          periodSeconds: 30
          httpGet:
            path: /health/ready
            port: 8080  