---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hidden-dependency
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: interest
  template:
    metadata:
      labels:
        app: interest
    spec:
      containers:
      - name: interest
        image: docker.io/kostiscodefresh/interest:{{CF_SHORT_REVISION}} 
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080        
